---

num_hosts: 144
num_tors: 9
num_aggr: 4
host_placement: "uniform"
leaf_link_speed_gbps: 25
core_link_speed_gbps: 40
core_link_latency_ms: 0.008
leaf_link_latency_ms: 0.005 

hosts:
  0: &tor0_r2p2
    tor: 0
    client: true
    server: true
    transport: micro-hybrid
  1: *tor0_r2p2
  2: *tor0_r2p2
  3: *tor0_r2p2
  4: *tor0_r2p2
  5: *tor0_r2p2
  6: *tor0_r2p2
  7: *tor0_r2p2

  8: &tor0_dctcp
    tor: 0
    client: true
    server: true
    transport: dctcp
  9: *tor0_dctcp
  10: *tor0_dctcp
  11: *tor0_dctcp
  12: *tor0_dctcp
  13: *tor0_dctcp
  14: *tor0_dctcp
  15: *tor0_dctcp

  16: &tor1_r2p2
    tor: 1
    client: true
    server: true
    transport: micro-hybrid
  17: *tor1_r2p2
  18: *tor1_r2p2
  19: *tor1_r2p2
  20: *tor1_r2p2
  21: *tor1_r2p2
  22: *tor1_r2p2
  23: *tor1_r2p2

  24: &tor1_dctcp
    tor: 1
    client: true
    server: true
    transport: dctcp
  25: *tor1_dctcp
  26: *tor1_dctcp
  27: *tor1_dctcp
  28: *tor1_dctcp
  29: *tor1_dctcp
  30: *tor1_dctcp
  31: *tor1_dctcp

  32: &tor2_r2p2
    tor: 2
    client: true
    server: true
    transport: micro-hybrid
  33: *tor2_r2p2
  34: *tor2_r2p2
  35: *tor2_r2p2
  36: *tor2_r2p2
  37: *tor2_r2p2
  38: *tor2_r2p2
  39: *tor2_r2p2

  40: &tor2_dctcp
    tor: 2
    client: true
    server: true
    transport: dctcp
  41: *tor2_dctcp
  42: *tor2_dctcp
  43: *tor2_dctcp
  44: *tor2_dctcp
  45: *tor2_dctcp
  46: *tor2_dctcp
  47: *tor2_dctcp

  48: &tor3_r2p2
    tor: 3
    client: true
    server: true
    transport: micro-hybrid
  49: *tor3_r2p2
  50: *tor3_r2p2
  51: *tor3_r2p2
  52: *tor3_r2p2
  53: *tor3_r2p2
  54: *tor3_r2p2
  55: *tor3_r2p2

  56: &tor3_dctcp
    tor: 3
    client: true
    server: true
    transport: dctcp
  57: *tor3_dctcp
  58: *tor3_dctcp
  59: *tor3_dctcp
  60: *tor3_dctcp
  61: *tor3_dctcp
  62: *tor3_dctcp
  63: *tor3_dctcp

  64: &tor4_r2p2
    tor: 4
    client: true
    server: true
    transport: micro-hybrid
  65: *tor4_r2p2
  66: *tor4_r2p2
  67: *tor4_r2p2
  68: *tor4_r2p2
  69: *tor4_r2p2
  70: *tor4_r2p2
  71: *tor4_r2p2

  72: &tor4_dctcp
    tor: 4
    client: true
    server: true
    transport: dctcp
  73: *tor4_dctcp
  74: *tor4_dctcp
  75: *tor4_dctcp
  76: *tor4_dctcp
  77: *tor4_dctcp
  78: *tor4_dctcp
  79: *tor4_dctcp

  80: &tor5_r2p2
    tor: 5
    client: true
    server: true
    transport: micro-hybrid
  81: *tor5_r2p2
  82: *tor5_r2p2
  83: *tor5_r2p2
  84: *tor5_r2p2
  85: *tor5_r2p2
  86: *tor5_r2p2
  87: *tor5_r2p2

  88: &tor5_dctcp
    tor: 5
    client: true
    server: true
    transport: dctcp
  89: *tor5_dctcp
  90: *tor5_dctcp
  91: *tor5_dctcp
  92: *tor5_dctcp
  93: *tor5_dctcp
  94: *tor5_dctcp
  95: *tor5_dctcp

  96: &tor6_r2p2
    tor: 6
    client: true
    server: true
    transport: micro-hybrid
  97: *tor6_r2p2
  98: *tor6_r2p2
  99: *tor6_r2p2
  100: *tor6_r2p2
  101: *tor6_r2p2
  102: *tor6_r2p2
  103: *tor6_r2p2

  104: &tor6_dctcp
    tor: 6
    client: true
    server: true
    transport: dctcp
  105: *tor6_dctcp
  106: *tor6_dctcp
  107: *tor6_dctcp
  108: *tor6_dctcp
  109: *tor6_dctcp
  110: *tor6_dctcp
  111: *tor6_dctcp

  112: &tor7_r2p2
    tor: 7
    client: true
    server: true
    transport: micro-hybrid
  113: *tor7_r2p2
  114: *tor7_r2p2
  115: *tor7_r2p2
  116: *tor7_r2p2
  117: *tor7_r2p2
  118: *tor7_r2p2
  119: *tor7_r2p2

  120: &tor7_dctcp
    tor: 7
    client: true
    server: true
    transport: dctcp
  121: *tor7_dctcp
  122: *tor7_dctcp
  123: *tor7_dctcp
  124: *tor7_dctcp
  125: *tor7_dctcp
  126: *tor7_dctcp
  127: *tor7_dctcp

  128: &tor8_r2p2
    tor: 8
    client: true
    server: true
    transport: micro-hybrid
  129: *tor8_r2p2
  130: *tor8_r2p2
  131: *tor8_r2p2
  132: *tor8_r2p2
  133: *tor8_r2p2
  134: *tor8_r2p2
  135: *tor8_r2p2

  136: &tor8_dctcp
    tor: 8
    client: true
    server: true
    transport: dctcp
  137: *tor8_dctcp
  138: *tor8_dctcp
  139: *tor8_dctcp
  140: *tor8_dctcp
  141: *tor8_dctcp
  142: *tor8_dctcp
  143: *tor8_dctcp
