---

num_hosts: 128
num_tors: 2
num_aggr: 1
host_placement: "manual"
leaf_link_speed_gbps: 10
core_link_speed_gbps: 100

hosts:
  0: &tor0
    tor: 0
    client: true
    server: false
  1: *tor0
  2: *tor0
  3: *tor0
  4: *tor0
  5: *tor0
  6: *tor0
  7: *tor0
  8: *tor0
  9: *tor0
  10: *tor0
  11: *tor0
  12: *tor0
  13: *tor0
  14: *tor0
  15: *tor0
  16: *tor0
  17: *tor0
  18: *tor0
  19: *tor0
  20: *tor0
  21: *tor0
  22: *tor0
  23: *tor0
  24: *tor0
  25: *tor0
  26: *tor0
  27: *tor0
  28: *tor0
  29: *tor0
  30: *tor0
  31: *tor0
  32: *tor0
  33: *tor0
  34: *tor0
  35: *tor0
  36: *tor0
  37: *tor0
  38: *tor0
  39: *tor0
  40: *tor0
  41: *tor0
  42: *tor0
  43: *tor0
  44: *tor0
  45: *tor0
  46: *tor0
  47: *tor0
  48: *tor0
  49: *tor0
  50: *tor0
  51: *tor0
  52: *tor0
  53: *tor0
  54: *tor0
  55: *tor0
  56: *tor0
  57: *tor0
  58: *tor0
  59: *tor0
  60: *tor0
  61: *tor0
  62: *tor0
  63: *tor0
  64: &tor1
    tor: 1
    client: false
    server: true
  65: *tor1
  66: *tor1
  67: *tor1
  68: *tor1
  69: *tor1
  70: *tor1
  71: *tor1
  72: *tor1
  73: *tor1
  74: *tor1
  75: *tor1
  76: *tor1
  77: *tor1
  78: *tor1
  79: *tor1
  80: *tor1
  81: *tor1
  82: *tor1
  83: *tor1
  84: *tor1
  85: *tor1
  86: *tor1
  87: *tor1
  88: *tor1
  89: *tor1
  90: *tor1
  91: *tor1
  92: *tor1
  93: *tor1
  94: *tor1
  95: *tor1
  96: *tor1
  97: *tor1
  98: *tor1
  99: *tor1
  100: *tor1
  101: *tor1
  102: *tor1
  103: *tor1
  104: *tor1
  105: *tor1
  106: *tor1
  107: *tor1
  108: *tor1
  109: *tor1
  110: *tor1
  111: *tor1
  112: *tor1
  113: *tor1
  114: *tor1
  115: *tor1
  116: *tor1
  117: *tor1
  118: *tor1
  119: *tor1
  120: *tor1
  121: *tor1
  122: *tor1
  123: *tor1
  124: *tor1
  125: *tor1
  126: *tor1
  127: *tor1

